on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          include-component-in-tag: false
      - name: create major release branch
        if: ${{ steps.release.outputs.release_created && steps.release.outputs.patch == 0 }}
        uses: peterjgrainger/action-create-branch@v2.2.0
        with:
          branch: "release/v${{ steps.release.outputs.major }}.0"
          sha: '${{ github.sha }}'