on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: create-release

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: release-please
        id: release_please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          include-component-in-tag: false
      - name: create major release branch
        if: ${{ steps.release_please.outputs.release_created && steps.release_please.outputs.patch == 0 }}
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "release/v${{ steps.release_please.outputs.major }}.${{ steps.release_please.outputs.minor }}.0"
          sha: '${{ github.sha }}'