on:
  push:
    branches:
      - 'release/**'

permissions:
  contents: write
  pull-requests: write

name: update-release

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - name: release-please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          include-component-in-tag: false
          versioning: always-bump-patch
          target-branch: ${{ github.ref_name }}